# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170723_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=400),
        ),
    ]
