# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_sessiontoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=400),
        ),
    ]
